#!/bin/bash
# STRIPE MULTI-CONTA - CHECKLIST DE IMPLEMENTAÇÃO
# Este arquivo contém um checklist completo para implementar a arquitetura

# ============================================================================
# FASE 1: CONFIGURAÇÃO NO STRIPE DASHBOARD
# ============================================================================

echo "📋 FASE 1: CONFIGURAÇÃO NO STRIPE DASHBOARD"
echo ""
echo "CONTA PJ (ANTIGA)"
echo "═════════════════════════════════════════════════════════════"
echo "[ ] 1. Acessar https://dashboard.stripe.com (conta PJ)"
echo "[ ] 2. Ir para Developers → API Keys"
echo "[ ] 3. Copiar Secret Key (começa com sk_test_ ou sk_live_)"
echo "[ ] 4. Salvar como: STRIPE_SECRET_KEY_PJ=sk_test_..."
echo ""
echo "[ ] 5. Criar/Atualizar Webhook"
echo "      • Developers → Webhooks → Add endpoint"
echo "      • URL: https://seu-dominio.com/webhook/stripe/pj"
echo "      • Eventos a selecionar:"
echo "        ✓ invoice.paid"
echo "        ✓ invoice.payment_failed"
echo "        ✓ customer.subscription.deleted"
echo "        ✓ customer.subscription.updated"
echo "        ✓ invoice.created"
echo "[ ] 6. Copiar Signing secret e salvar como: STRIPE_WEBHOOK_SECRET_PJ=whsec_..."
echo ""
echo ""
echo "CONTA PF (NOVA)"
echo "═════════════════════════════════════════════════════════════"
echo "[ ] 7. Acessar https://dashboard.stripe.com (conta PF)"
echo "[ ] 8. Ir para Developers → API Keys"
echo "[ ] 9. Copiar Secret Key"
echo "[ ] 10. Salvar como: STRIPE_SECRET_KEY_PF=sk_test_..."
echo ""
echo "[ ] 11. CRIAR NOVOS PREÇOS em PF"
echo "       • Ir para Products"
echo "       • Crie um produto 'VIP Diamond' com preços:"
echo "         - Diamond Monthly → Copiar Price ID para STRIPE_PRICEID_PF_DIAMOND_MONTHLY"
echo "         - Diamond Annual → Copiar Price ID para STRIPE_PRICEID_PF_DIAMOND_ANNUAL"
echo "       • Crie um produto 'VIP Lifetime' com:"
echo "         - Lifetime (um-pagamento) → Copiar para STRIPE_PRICEID_PF_LIFETIME"
echo ""
echo "[ ] 12. Criar Webhook para PF"
echo "       • Developers → Webhooks → Add endpoint"
echo "       • URL: https://seu-dominio.com/webhook/stripe/pf"
echo "       • Eventos:"
echo "         ✓ checkout.session.completed"
echo "         ✓ invoice.paid"
echo "         ✓ invoice.payment_failed"
echo "         ✓ customer.subscription.deleted"
echo "         ✓ customer.subscription.updated"
echo "         ✓ invoice.created"
echo "[ ] 13. Copiar Signing secret e salvar como: STRIPE_WEBHOOK_SECRET_PF=whsec_..."
echo ""
echo ""

# ============================================================================
# FASE 2: ARQUIVO .ENV
# ============================================================================

echo "📄 FASE 2: CONFIGURAR .ENV"
echo "═════════════════════════════════════════════════════════════"
echo "[ ] 14. Abrir arquivo: BACKEND/.env"
echo "[ ] 15. Preencher as variáveis de STRIPE:"
echo ""
echo "STRIPE_SECRET_KEY_PJ=sk_test_YOUR_PJ_KEY"
echo "STRIPE_WEBHOOK_SECRET_PJ=whsec_YOUR_PJ_SECRET"
echo "STRIPE_SECRET_KEY_PF=sk_test_YOUR_PF_KEY"
echo "STRIPE_WEBHOOK_SECRET_PF=whsec_YOUR_PF_SECRET"
echo "STRIPE_PRICEID_PF_DIAMOND_MONTHLY=price_XXX"
echo "STRIPE_PRICEID_PF_DIAMOND_ANNUAL=price_XXX"
echo "STRIPE_PRICEID_PF_LIFETIME=price_XXX"
echo ""
echo "[ ] 16. Salvar arquivo .env"
echo ""
echo ""

# ============================================================================
# FASE 3: VERIFICAR ARQUIVOS CRIADOS
# ============================================================================

echo "✅ FASE 3: ARQUIVOS JÁ CRIADOS/ATUALIZADOS"
echo "═════════════════════════════════════════════════════════════"
echo "[ ] 17. Verificar lib/stripeService.js (✅ Criado)"
echo "        • getStripeInstance(operation, context)"
echo "        • verifyWebhookSignature(body, sig)"
echo "        • identifySubscriptionAccount(subscriptionId)"
echo "        • getPriceId(vipTier, planType)"
echo ""
echo "[ ] 18. Verificar routes/payment.js (✅ Atualizado)"
echo "        • Importa stripeService"
echo "        • Usa getStripeInstance('create')"
echo "        • Usa getPriceId()"
echo "        • TITANIUM comentado"
echo ""
echo "[ ] 19. Verificar routes/stripewebhook.js (✅ Atualizado)"
echo "        • Importa stripeService"
echo "        • Usa verifyWebhookSignature()"
echo "        • Detecta conta automaticamente"
echo ""
echo "[ ] 20. Ler documentação:"
echo "        • STRIPE_ARCHITECTURE.md"
echo "        • STRIPE_SETUP_GUIDE.md"
echo "        • STRIPE_INTEGRATION_EXAMPLES.js"
echo ""
echo ""

# ============================================================================
# FASE 4: OUTRAS ROTAS QUE PRECISAM ATUALIZAR
# ============================================================================

echo "🔧 FASE 4: ROTAS QUE FALTAM ATUALIZAR"
echo "═════════════════════════════════════════════════════════════"
echo "[ ] 21. Atualizar routes/Cancelsubscription.js"
echo "        • Importar stripeService"
echo "        • Usar identifySubscriptionAccount()"
echo "        • Selecionar stripe correta (PJ ou PF)"
echo "        • Exemplo em: STRIPE_INTEGRATION_EXAMPLES.js"
echo ""
echo "[ ] 22. Atualizar routes/Renewvip.js (se existir)"
echo "        • Importar stripeService"
echo "        • Usar getStripeInstance('renew')"
echo "        • Sempre usar stripePF"
echo ""
echo "[ ] 23. Atualizar routes/stripeCustomerPortal.js (se existir)"
echo "        • Importar stripeService"
echo "        • Identificar conta do cliente"
echo "        • Usar stripe correspondente"
echo ""
echo ""

# ============================================================================
# FASE 5: TESTES LOCAIS
# ============================================================================

echo "🧪 FASE 5: TESTES LOCAIS"
echo "═════════════════════════════════════════════════════════════"
echo "[ ] 24. Instalar Stripe CLI (se não tiver)"
echo "        curl https://files.stripe.com/stripe-cli/install.sh | bash"
echo ""
echo "[ ] 25. Terminal 1: Escutar webhooks PJ"
echo "        stripe listen --forward-to localhost:3000/webhook/stripe/pj"
echo "        • Copiar signing secret em .env como STRIPE_WEBHOOK_SECRET_PJ"
echo ""
echo "[ ] 26. Terminal 2: Escutar webhooks PF"
echo "        stripe listen --forward-to localhost:3000/webhook/stripe/pf"
echo "        • Copiar signing secret em .env como STRIPE_WEBHOOK_SECRET_PF"
echo ""
echo "[ ] 27. Terminal 3: Iniciar servidor"
echo "        npm start"
echo ""
echo "[ ] 28. Testar criação de checkout (PF)"
echo "        curl -X POST http://localhost:3000/vip-payment \\
echo "          -H 'Content-Type: application/json' \\
echo "          -d '{\"email\":\"test@example.com\",\"vipTier\":\"diamond\",\"planType\":\"monthly\"}'"
echo ""
echo "[ ] 29. Simular webhook"
echo "        stripe trigger checkout.session.completed"
echo ""
echo "[ ] 30. Verificar logs (deve mostrar 'Conta: PF')"
echo ""
echo ""

# ============================================================================
# FASE 6: TESTES DE CANCELAMENTO
# ============================================================================

echo "❌ FASE 6: TESTES DE CANCELAMENTO"
echo "═════════════════════════════════════════════════════════════"
echo "[ ] 31. Testar cancelamento de assinatura NOVA (PF)"
echo "        • Criar assinatura em PF"
echo "        • Cancelar usando subscription ID de PF"
echo "        • Deve usar stripePF"
echo ""
echo "[ ] 32. Testar cancelamento de assinatura LEGADO (PJ)"
echo "        • Encontrar subscription ID antigo (PJ)"
echo "        • Cancelar usando esse ID"
echo "        • Deve usar stripePJ"
echo ""
echo "[ ] 33. Verificar identifySubscriptionAccount()"
echo "        • Chamar com sub PF → deve retornar 'pf'"
echo "        • Chamar com sub PJ → deve retornar 'pj'"
echo ""
echo ""

# ============================================================================
# FASE 7: DEPLOYMENT
# ============================================================================

echo "🚀 FASE 7: DEPLOYMENT"
echo "═════════════════════════════════════════════════════════════"
echo "[ ] 34. Verificar variáveis de ambiente em produção"
echo "        • STRIPE_SECRET_KEY_PJ (production key)"
echo "        • STRIPE_SECRET_KEY_PF (production key)"
echo "        • STRIPE_WEBHOOK_SECRET_PJ (production)"
echo "        • STRIPE_WEBHOOK_SECRET_PF (production)"
echo ""
echo "[ ] 35. Configurar webhooks em produção"
echo "        PJ Dashboard: https://seu-dominio-prod.com/webhook/stripe/pj"
echo "        PF Dashboard: https://seu-dominio-prod.com/webhook/stripe/pf"
echo ""
echo "[ ] 36. Copiar signing secrets de produção para .env.production"
echo ""
echo "[ ] 37. Deploy em produção"
echo "        git push production main"
echo ""
echo "[ ] 38. Verificar logs de webhook em produção"
echo "        Deve mostrar 'Conta: pj' ou 'Conta: pf' dependendo do evento"
echo ""
echo ""

# ============================================================================
# FASE 8: MONITORAMENTO
# ============================================================================

echo "📊 FASE 8: MONITORAMENTO"
echo "═════════════════════════════════════════════════════════════"
echo "[ ] 39. Monitorar logs de webhook"
echo "        tail -f /var/log/app.log | grep WEBHOOK"
echo ""
echo "[ ] 40. Verificar eventos no Stripe Dashboard"
echo "        PJ: Developers → Webhooks → Events (deve ver legacy events)"
echo "        PF: Developers → Webhooks → Events (deve ver novos events)"
echo ""
echo "[ ] 41. Alertas para erros"
echo "        • Webhook signature inválida"
echo "        • Subscription not found"
echo "        • Price not configured"
echo ""
echo "[ ] 42. Testar migração de cliente (se necessário)"
echo "        • Cancelar em PJ"
echo "        • Criar em PF"
echo "        • Marcar user.stripeAccountOrigin = 'pf'"
echo ""
echo ""

# ============================================================================
# RESUMO FINAL
# ============================================================================

echo "✨ RESUMO FINAL"
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "Total de itens: 42"
echo ""
echo "Quando este checklist estiver completo, você terá:"
echo "✅ Duas contas Stripe funcionando em paralelo"
echo "✅ PJ para assinaturas legadas (apenas webhooks e cancelamento)"
echo "✅ PF para novas assinaturas (criação, renovação, webhooks)"
echo "✅ Sistema que detecta automaticamente qual conta usar"
echo "✅ Webhooks separados funcionando corretamente"
echo "✅ Código pronto para produção"
echo ""
echo "═════════════════════════════════════════════════════════════"
echo ""
echo "Dúvidas? Ver:"
echo "  • STRIPE_ARCHITECTURE.md"
echo "  • STRIPE_SETUP_GUIDE.md"
echo "  • STRIPE_INTEGRATION_EXAMPLES.js"
echo ""
